services:
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    volumes:
        # - ./neo4j/logs:/logs
        # - ./neo4j/data:/data
        - ./import:/import
    environment:
        - NEO4J_AUTH=neo4j/neo4j_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always