services:
  hazelcast:
    scale: 3
    image: hazelcast/hazelcast:5.4.0
    ports:
      - 5701

  management-center:
    image: hazelcast/management-center:5.4.0
    environment:
      - MC_DEFAULT_CLUSTER=counter
      - MC_DEFAULT_CLUSTER_MEMBERS=hazelcast:5701
      - MC_ALLOW_MULTIPLE_LOGIN=true
      - MC_ADMIN_USER=admin
      - MC_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
