services:
    hz-1:
        container_name: hz-1
        image: hazelcast/hazelcast:5.4.0
        ports:
            - 5701:5701
        environment:
            - HZ_CLUSTERNAME=counter
            - HZ_NETWORK_PUBLICADDRESS=172.20.0.20:5701
            - JAVA_OPTS=-Dhazelcast.config=/project/hazelcast.yaml
        volumes:
            - "./volume:/project"
        networks:
            - hazelcast-network
    hz-2:
        container_name: hz-2
        image: hazelcast/hazelcast:5.4.0
        ports:
            - 5702:5701
        environment:
            - HZ_CLUSTERNAME=counter
            - HZ_NETWORK_PUBLICADDRESS=172.20.0.20:5702
            - JAVA_OPTS=-Dhazelcast.config=/project/hazelcast.yaml
        volumes:
            - "./volume:/project"
        networks:
            - hazelcast-network
    hz-3:
        container_name: hz-3
        image: hazelcast/hazelcast:5.4.0
        ports:
            - 5703:5701
        environment:
            - HZ_CLUSTERNAME=counter
            - HZ_NETWORK_PUBLICADDRESS=172.20.0.20:5703
            - JAVA_OPTS=-Dhazelcast.config=/project/hazelcast.yaml
        volumes:
            - "./volume:/project"
        networks:
            - hazelcast-network
    management-center:
        container_name: manager
        image: hazelcast/management-center:5.4.0
        ports:
            - 8080:8080
        environment:
        - MC_DEFAULT_CLUSTER=counter
        - MC_DEFAULT_CLUSTER_MEMBERS=hz-1,hz-2,hz-3
        networks:
            - hazelcast-network
networks:
    hazelcast-network:
        name: hazelcast-network
