# comment user and password for now experiment
services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo1", "--port", "27017"]
    ports:
      - 27017:27017
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
      - ${PWD}/initiate_replica_set.mongodb:/tmp/initiate_replica_set.mongodb
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: password
    post_start:
      # - command: bash -c "sleep 10 && mongosh -u user -p password -f /tmp/initiate_replica_set.mongodb"
      - command: bash -c "sleep 5 && mongosh -f /tmp/initiate_replica_set.mongodb"
        working_dir: /
        user: root
        privileged: true
    networks:
      mongoCluster:
         
  mongo2:
    container_name: mongo2
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo2", "--port", "27018"]
    ports:
      - 27018:27018
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      mongoCluster:

  mongo3:
    container_name: mongo3
    image: mongo:latest
    command: ["--replSet", "rs0", "--bind_ip", "localhost,mongo3", "--port", "27019"]
    ports:
      - 27019:27019
    volumes:
      - ${PWD}/rs_keyfile:/etc/mongodb/pki/keyfile
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      mongoCluster:

networks:
  mongoCluster:
    name: mongoCluster
